version: "3.8"
services:
  openvpn-as:
    image: bulut/openvpn-as
#    container_name: openvpn-as
    cap_add:
      - NET_ADMIN #required!
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
#      - INTERFACE=eth0 #optional
    volumes:
      - openvpn_config:/config
    ports:
      - 943:943
      - 9443:9443
      - 1194:1194/udp
    restart: unless-stopped

volumes:
  openvpn_config:
